name: OSV-Scanner Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9:00 AM UTC
permissions:
  actions: read
  security-events: write
  contents: read
jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: google/osv-scanner-action/osv-scanner-action@v2.3.8
        continue-on-error: true
        with:
          scan-args: -r ./
